version: '3.8'

services:
  service1:
    image: python:3.8-slim
    container_name: python_service1
    volumes:
      - ./service1:/app
    working_dir: /app
    command: python -u app.py

  service2:
    image: python:3.8-slim
    container_name: python_service2
    volumes:
      - ./service2:/app
    working_dir: /app
    command: python -u app.py